apiVersion: v2
name: osc-open-webui
description: OSC Open Web UI deployment
type: application
version: 0.5.3
appVersion: "0.1.0"
maintainers:
  - name: treydock
dependencies:
  - name: osc-common
    version: 0.9.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../common
  - name: open-webui
    version: 12.3.0
    repository: https://helm.openwebui.com/
