apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.auth.name" . }}
  labels:
    {{- include "cryosparc.auth.labels" . | nindent 4 }}
  {{- if (include "cryosparc.alert.receiver" .) }}
    receiver: {{ include "cryosparc.alert.receiver" . }}
  {{- end }}
  {{- with .Values.auth.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "cryosparc.auth.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryosparc.auth.name" . }}-metrics
  labels:
    {{- include "cryosparc.auth.labels" . | nindent 4 }}
  {{- if (include "cryosparc.alert.receiver" .) }}
    receiver: {{ include "cryosparc.alert.receiver" . }}
  {{- end }}
  {{- with .Values.auth.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.auth.metricsService.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "cryosparc.auth.selectorLabels" . | nindent 4 }}
