{{- if .Values.global.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osc.common.imagePullSecret.name" .| quote }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "osc.common.imagePullSecret" . }}
{{- end }}
