kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cryosparc.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "cryosparc.auth.selectorLabels" . | nindent 10 }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.ingressName }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.prometheusName }}
