apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.license | b64enc }}
  email: b3Njc29mdEBvc2MuZWR1
  username: b3Njc29mdA==
  password: U2NpQXBwc1Rlc3QxMjI0
