apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
type: Opaque
data:
  username: b3Njc29mdAo=
  password: U2NpQXBwc1Rlc3QxMjI0Cg==
