apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.license | b64enc }}
  email: {{ .Values.adminSciapps.email | b64enc }}
  username: {{ .Values.adminSciapps.username | b64enc }}
  password: {{ .Values.adminSciapps.password | b64enc }}
