apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryosparc.name" . }}
  labels:
    {{- include "cryosparc.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "osc.common.imagePullSecret.name" . }}
