global:
  oscServiceAccount: cryosciapps
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
maintenance:
  groups:
    - foo
    - bar
nodeSelector:
  kubernetes.io/os: linux
auth:
  clientSecret: b8a873d4-e662-496c-ad43-26596eaff68c
  cookieSecret: PwRlaBzY3aBtKvshJzlMpxyfAp6AZg7orRoKz3NtuJw=
  oidcIssuerURL: http://keycloak.keycloak.svc.cluster.local/realms/master
alert:
  receiver: test
debugGroups:
  - foobar
image:
  tag: latest
ingress:
  host: cryosciapps.osc.edu
podSecurityContext:
  runAsUser: 48527
  runAsGroup: 5511
  fsGroup: 5511
service:
  basePort: 31010
mockNodes:
  - kubeworker21
  - kubeworker23
license: xxx-xxx-xxx
project: PAS0710
