apiVersion: v2
name: prometheus
description: OSC Prometheus deployment
type: application
version: 0.19.1
appVersion: "v2.44.0"
maintainers:
  - name: treydock
dependencies:
  - name: kube-state-metrics
    version: 5.6.2
    repository: https://prometheus-community.github.io/helm-charts/
  - name: dcgm-exporter
    version: 4.6.0
    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
  - name: osc-common
    version: 0.5.0
    repository: https://osc.github.io/osc-helm-charts/
    # repository: file://../common
