{{- $replicas := .Values.auth.replicas | default 1 }}
{{- if and .Values.auth.enable (gt (int $replicas) 1 ) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "osc-open-webui.auth.name" . }}
  labels:
    {{- include "osc-open-webui.auth.labels" . | nindent 4 }}
spec:
  {{- if .Values.auth.podDistributionBudget.minAvailable }}
  minAvailable: {{ .Values.auth.podDistributionBudget.minAvailable }}
  {{- else if .Values.auth.podDistributionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.auth.podDistributionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osc-open-webui.auth.selectorLabels" . | nindent 6 }}
{{- end }}
