{{ if .Values.auth.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osc-open-webui.auth.name" . }}
  labels:
    {{- include "osc-open-webui.auth.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "osc.common.imagePullSecret.name" . }}
{{ end }}
