{{ if .Values.auth.enable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osc-open-webui.auth.name" . }}
  labels:
    {{- include "osc-open-webui.auth.labels" . | nindent 4 }}
  {{- if .Values.global.alert.receiver }}
    receiver: {{ .Values.global.alert.receiver }}
  {{- end }}
  annotations:
    prometheus.io/probe_scheme: 'https'
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    prometheus.io/probe_path: /ping
    #nginx.ingress.kubernetes.io/enable-cors: 'true'
    {{- if .Values.global.ingress.hostAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ tpl .Values.global.ingress.hostAlias . }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ required "Must provide ingress host" (tpl .Values.global.ingress.host .) | quote }}
  {{- if .Values.global.ingress.hostAlias }}
    - {{ tpl .Values.global.ingress.hostAlias . | quote }}
  {{- end }}
    secretName: {{ include "osc-open-webui.name" . }}-cert
  rules:
  - host: {{ tpl .Values.global.ingress.host . | quote }}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: {{ include "osc-open-webui.auth.name" . }}
            port:
              number: {{ .Values.auth.service.port }}
      - path: /ping
        pathType: Prefix
        backend:
          service:
            name: {{ include "osc-open-webui.auth.name" . }}
            port:
              number: {{ .Values.auth.service.port }}
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osc-open-webui.name" . }}
  labels:
    {{- include "osc-open-webui.labels" . | nindent 4 }}
  {{- if .Values.global.alert.receiver }}
    receiver: {{ .Values.global.alert.receiver }}
  {{- end }}
  annotations:
    prometheus.io/probe_scheme: 'https'
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    #nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers:
      x-auth-request-preferred-username, x-auth-request-email, x-auth-request-groups
    {{- if .Values.global.ingress.hostAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ tpl .Values.global.ingress.hostAlias . }}
    {{- end }}
spec:
  ingressClassName: nginx
{{- if not .Values.auth.enable }}
  tls:
  - hosts:
    - {{ required "Must provide ingress host" (tpl .Values.global.ingress.host .) | quote }}
  {{- if .Values.global.ingress.hostAlias }}
    - {{ tpl .Values.global.ingress.hostAlias . | quote }}
  {{- end }}
    secretName: {{ include "osc-open-webui.name" . }}-cert
{{- end }}
  rules:
  - host: {{ tpl .Values.global.ingress.host . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ index .Values "open-webui" "nameOverride" }}
            port:
              name: http
{{- if .Values.auth.enable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osc-open-webui.api.name" . }}
  labels:
    {{- include "osc-open-webui.api.labels" . | nindent 4 }}
  {{- if .Values.global.alert.receiver }}
    receiver: {{ .Values.global.alert.receiver }}
  {{- end }}
  annotations:
    prometheus.io/probe_scheme: 'https'
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    {{- if .Values.global.ingress.hostAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ include "osc-open-webui.api.hostAlias" . | quote }}
    {{- end }}
    {{- if .Values.global.ingress.apiAllowedRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.global.ingress.apiAllowedRange | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ include "osc-open-webui.api.host" . | quote }}
  {{- if .Values.global.ingress.hostAlias }}
    - {{ include "osc-open-webui.api.hostAlias" . | quote }}
  {{- end }}
    secretName: {{ include "osc-open-webui.api.name" . }}-cert
  rules:
  - host: {{ include "osc-open-webui.api.host" . | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ index .Values "open-webui" "nameOverride" }}
            port:
              name: http
      - path: /ollama/api
        pathType: Prefix
        backend:
          service:
            name: {{ index .Values "open-webui" "nameOverride" }}
            port:
              name: http
{{- end }}
