# https://github.com/kyverno/policies/blob/main/other/sync-secrets/sync-secrets.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
spec:
  rules:
  - name: sync-image-pull-secret
    match:
      resources:
        kinds:
        - Namespace
        selector:
          matchLabels:
            sync-secret: '*'
    generate:
      apiVersion: v1
      kind: Secret
      name: "{{`{{request.object.metadata.labels.sync-secret}}`}}-gen"
      namespace: "{{`{{request.object.metadata.name}}`}}"
      synchronize: true
      clone:
        namespace: default
        name: "{{`{{request.object.metadata.labels.sync-secret}}`}}"
