---
global:
  nodeSelectorRole: test
  networkPolicy:
    podSelector:
      app.kubernetes.io/name: test
    ingressAllowedPods:
      - require: foo
      - app.kubernetes.io/name: '{{ include "osc.common.name" . }}'
  debugGroups:
    - testdebug
    - testdebug2
  maintenanceGroups:
    - testmaint
    - testmaint2
  portforwardGroups:
    - portforward
    - portforward2
