---
global:
  nodeSelectorRole: test
  networkPolicy:
    podSelector:
      app.kubernetes.io/name: test
    ingressLabels:
      - require: foo
  debugGroups:
    - testdebug
    - testdebug2
  maintenanceGroups:
    - testmaint
    - testmaint2
  portforwardGroups:
    - portforward
    - portforward2
