{{- if .Values.global.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "osc.common.name" . }}-{{ include "osc.common.imagePullSecret.name" . }}'
  labels:
    {{- include "osc.common.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "osc.common.imagePullSecret" . }}
{{- end }}
