{{- if .Values.global.networkPolicy.create }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "osc.common.name" . }}
  labels:
    {{- include "osc.common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- if .Values.global.networkPolicy.podSelector }}
      {{- tpl (toYaml .Values.global.networkPolicy.podSelector) . | nindent 6 }}
    {{- else }}
      {{- include "osc.common.selectorLabels" . | nindent 6 }}
    {{- end }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "osc.common.selectorLabels" . | nindent 10 }}
    {{- range $labels := .Values.global.networkPolicy.ingressAllowedPods  }}
    - podSelector:
        matchLabels:
          {{-  tpl (toYaml $labels) $ | nindent 10 }}
    {{- end }}
    {{- if .Values.global.networkPolicy.ingressNamespace }}
    - namespaceSelector:
        {{- $ingressNamespace := lookup "v1" "Namespace" "" .Values.global.networkPolicy.ingressNamespace }}
        {{- if and $ingressNamespace $ingressNamespace.metadata.labels }}
        matchLabels:
          {{- range $key, $value := $ingressNamespace.metadata.labels }}
          {{ $key }}: {{ $value }}
          {{- end }}
        {{- else }}
        matchLabels:
          app.kubernetes.io/name: {{ .Values.global.networkPolicy.ingressNamespace }}
        {{- end }}
    {{- end }}
    {{- if .Values.global.networkPolicy.prometheusNamespace }}
    - namespaceSelector:
        {{- $prometheusNamespace := lookup "v1" "Namespace" "" .Values.global.networkPolicy.prometheusNamespace }}
        {{- if and $prometheusNamespace $prometheusNamespace.metadata.labels }}
        matchLabels:
          {{- range $key, $value := $prometheusNamespace.metadata.labels }}
          {{ $key }}: {{ $value }}
          {{- end }}
        {{- else }}
        matchLabels:
          app.kubernetes.io/name: {{ .Values.global.networkPolicy.prometheusNamespace }}
        {{- end }}
    {{- end }}
{{- end }}
