{{- if .Values.global.webservicesDeploy.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: '{{ include "osc.common.name" . }}-webservices-deploy'
  labels:
    {{- include "osc.common.labels" . | nindent 4 }}
roleRef:
  # ClusterRole managed centrally inside OSC internal repo
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.webservicesDeploy.clusterRole | quote }}
subjects:
  # ServiceAccount managed centrally inside OSC internal repo
  - kind: ServiceAccount
    name: {{ .Values.global.webservicesDeploy.serviceAccount | quote }}
    namespace: default
{{- end }}
