global:
  oscServiceAccount: nobody
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
  maintenanceGroups:
    - testgroup
  portforwardGroups:
    - testgroup1
mongodb:
  enable: true
  persistence:
    enabled: true
    name: datadir
    mountPath: /bitnami/mongodb
    size: 50Mi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  initContainers: []
  extraVolumeMounts: []
  extraVolumes: []
