global:
  oscServiceAccount: nobody
  imagePullSecret:
    password: IMAGE-PULL-PASSWORD
  nodeSelectorRole: test
  storageClass: standard
redis:
  enable: true
  auth:
    password: secret
  master:
    persistence:
      size: 50Mi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
