global:
  oscServiceAccount: ouollama
  imagePullSecret:
    password: EXTERNAL-SECRET
  auth:
    idpHost: EXTERNAL-DATA
    clientID: EXTERNAL-DATA
    clientSecret: EXTERNAL-SECRET
    cookieSecret: EXTERNAL-SECRET
    allowGroups:
      - PHS0375
      - oscall
  maintenanceGroups:
    - oscstaff
  ingress:
    host: EXTERNAL-DATA
    hostAlias: EXTERNAL-DATA
  webui_secret_key: EXTERNAL-SECRET
  alert:
    receiver: sciapps
osc-open-webui:
  open-webui:
    extraLabels:
      receiver: sciapps
    podLabels:
      osc.edu/service-account: ouollama
      receiver: sciapps
    nodeSelector:
      node-role.kubernetes.io/webservices: ''
    service:
      labels:
        receiver: sciapps
    ollama:
      nodeSelector:
        # EXTERNAL-DATA
        # nvidia.com/gpu.product: NVIDIA-A100-PCIE-40GB-MIG-1g.5gb
        node-role.kubernetes.io/webservices: ''
      deployment:
        labels:
          osc.edu/service-account: ouollama
          receiver: sciapps
      podLabels:
        osc.edu/service-account: ouollama
        receiver: sciapps
      volumes:
      - name: data
        hostPath:
          path: /fs/ess/PHS0375
          type: Directory
      - name: home
        hostPath:
          path: /users/PHS0375/ouollama
          type: Directory
      service:
        labels:
          receiver: sciapps
