{{- if .Values.global.portforwardGroups }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "database.name" . }}-portforward
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "database.name" . }}-portforward
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "database.name" . }}-portforward
subjects:
{{- range .Values.global.portforwardGroups }}
  - kind: Group
    name: {{ . | quote }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}